-- AlterTable
ALTER TABLE "Review" ALTER COLUMN "teaId" DROP NOT NULL,
ALTER COLUMN "teaId" SET DATA TYPE TEXT;

-- AddForeignKey
ALTER TABLE "Review" ADD CONSTRAINT "Review_teaId_fkey" FOREIGN KEY ("teaId") REFERENCES "Tea"("id") ON DELETE SET NULL ON UPDATE CASCADE;
